#!/bin/bash

# This script has to be run as root and needs no parameters

USERUID=`id -u`

if [ "$USERUID" == "0" ]; then
    echo "  ______  ______ _     _ ______        _____  _______ _______ _______ _  _  _  _____   ______ ______  "
    echo " |  ____ |_____/ |     | |_____]      |_____] |_____| |______ |______ |  |  | |     | |_____/ |     \ "
    echo " |_____| |    \_ |_____| |_____]      |       |     | ______| ______| |__|__| |_____| |    \_ |_____/ "
    echo                                                            
    echo "Please type username to install (Grub will ask you for this username))."
    echo "Please note that this username does not have to be equal to your system username."
    read
    THEUSERNAME=${REPLY}
    echo "Username is $THEUSERNAME"
    echo "Please type a password (echoing is disabled)..."
    read -s
    FIRST="${REPLY}"
    echo "Please re-type the password..."
    read -s
    SECOND="${REPLY}"
    if [ "$FIRST" == "$SECOND" ]; then
        MYPASS=`echo -e "$FIRST\n$SECOND" | grub-mkpasswd-pbkdf2 | awk '/grub.pbkdf/{print$NF}'`
        echo "Appending data to 00_header."
	read -p "Do you want to continue?" -n 1 -r
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
	    echo "Aborted by user."
	    exit 0
	fi
        echo -e "\ncat << EOF\nset superusers=\"$THEUSERNAME\"\npassword_pbkdf2 $THEUSERNAME $MYPASS\nEOF" >> /etc/grub.d/00_header
	update-grub
	echo "Done. You may reboot now."
    else
        echo "The two passwords are different. Aborting..."
        exit 0
    fi
else
    echo "Please run this script as root..."
fi