#!/usr/bin/env bash

#Inform the user
echo "Updating VLC playlist scripts"

sudo rm -f /usr/lib/x86_64-linux-gnu/vlc/lua/playlist/youtube.lua
sudo wget -P /usr/lib/x86_64-linux-gnu/vlc/lua/playlist/ "https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua"
